#line 1 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\lex.yy.c"

#line 3 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 86
#define YY_END_OF_BUFFER 87
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[207] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   87,   85,
       84,    1,   67,   29,   66,   85,   68,   69,   64,   62,
       58,   63,   57,   65,   28,   28,   60,   59,   55,   54,
       56,   22,   22,   22,   22,   22,   22,   22,   22,   70,
       71,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   72,   85,   73,   82,   83,   82,   82,   76,   77,
       76,   30,   41,   42,   85,   84,   49,    0,   47,   53,
       46,   43,   44,   61,   79,   78,   45,    0,   28,    0,
        0,    0,    0,    0,    0,   50,   48,   51,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,

       22,   22,   22,   22,    6,   22,   22,   22,   22,   22,
       22,   52,   82,   81,   80,   76,   76,   30,   40,   39,
       34,   31,   33,   35,   32,   36,   37,   38,   74,   78,
       24,    0,   24,    0,   23,   25,   26,   27,   22,   22,
       22,   22,   22,   22,   16,   22,   22,   22,   22,   22,
        8,   22,    5,   13,   22,   22,    4,   22,   75,   24,
        0,   24,   24,   23,   25,   26,    0,   27,   22,   14,
       22,   22,   22,   20,   22,   17,   22,    7,   22,    3,
       22,   11,   22,    0,   24,   24,    0,   22,   22,   18,
       22,    2,   12,   22,    9,   24,    0,    0,   21,   19,

       15,   10,    0,   23,   23,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   26,   27,   26,   28,   29,   30,
       31,   31,   32,   31,   31,   31,   31,   33,   31,   34,
       31,   31,   35,   36,   37,   31,   31,   31,   31,   31,
       38,   39,   40,    1,   41,    1,   42,   43,   44,   26,

       45,   46,   47,   48,   49,   31,   31,   50,   31,   51,
       52,   34,   31,   53,   54,   55,   56,   57,   58,   59,
       31,   31,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        1,    4,    1,    4,    5,    1,    6,    6,    6,    6,
        1,    1,    1,    1,    1,    6,    6,    6,    6,    6,
        1,    1,    1,    7,    1,    1,    1,    1,    3,    1,
        8,    6,    6,    6,    6,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[220] =
    {   0,
        0,    0,   60,   61,   62,   63,   70,   75,  431,  459,
      421,  459,  391,  383,  363,  379,  459,  459,  360,  359,
      459,   45,  459,   63,  100,   38,  459,  459,  358,  357,
      356,  143,  327,   53,  328,  186,   50,  322,  343,  459,
      459,  324,  323,   42,  326,  326,  321,  324,  306,  316,
      309,  459,  289,  459,    0,  459,  333,  337,    0,  459,
      341,    0,  459,  459,  228,  343,  459,  339,  459,  459,
      459,  459,  459,  459,  459,    0,  459,   93,   43,  308,
      119,  137,   74,  104,    0,  459,  459,  459,    0,    0,
      205,  289,  308,  261,  264,  283,  258,  259,  260,  259,

      245,  234,  229,  227,    0,  222,  226,  218,  216,  216,
      215,  459,    0,    0,    0,    0,  257,    0,  459,  459,
      459,  459,  459,  459,  459,  459,  459,  459,  459,    0,
      220,  147,  234,  190,  239,  229,  225,  245,  269,  205,
      217,  205,  199,  199,    0,  185,  171,  167,  173,  157,
        0,  139,    0,    0,  126,  136,    0,  118,    0,  273,
      286,  302,    0,  306,    0,  290,    0,  143,  310,    0,
      115,   90,   80,    0,   81,    0,   71,    0,   79,    0,
       63,    0,   62,  277,  315,  319,   69,   64,   54,    0,
       49,    0,    0,   42,    0,  335,   55,   92,    0,    0,

        0,    0,  136,  344,  348,  459,  389,  397,  405,  413,
      421,  429,  437,  440,   82,  444,   79,  447,  452
    } ;

static const flex_int16_t yy_def[220] =
    {   0,
      206,    1,  207,  207,  208,  208,  209,  209,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,   25,  206,  206,  206,  206,
      206,  206,   32,   32,   32,   32,   36,   36,   36,  206,
      206,   32,   32,   32,   36,   36,   36,   36,   36,   36,
       36,  206,  206,  206,  210,  206,  210,  210,  211,  206,
      211,  212,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  213,  206,  206,   25,  214,
      214,  206,  214,  206,  215,  206,  206,  206,   32,   36,
       36,   36,   32,   36,   36,   36,   36,   36,   36,   36,

       36,   32,   36,   36,   36,   36,   36,   36,   36,   36,
       36,  206,  210,  210,  210,  211,  211,  212,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  213,
      206,  206,  214,  206,  206,  214,  206,  216,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,  211,  206,
      206,  206,  133,  206,  136,  206,  217,  216,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,  206,  206,  206,  218,   36,   36,   36,
       36,   36,   36,   36,   36,  206,  218,  219,   36,   36,

       36,   36,  219,  206,  206,    0,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206
    } ;

static const flex_int16_t yy_nxt[522] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   10,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   26,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   32,   35,
       36,   37,   36,   36,   38,   36,   39,   40,   10,   41,
       36,   32,   32,   42,   43,   44,   36,   36,   45,   46,
       47,   36,   48,   36,   49,   36,   50,   51,   36,   52,
       53,   54,   56,   56,   60,   60,   61,   61,   73,   74,
       57,   57,   63,   75,   64,   58,   58,   63,   76,   64,
       80,   93,   96,  102,  187,   80,   77,  138,  198,  206,
      136,  136,  202,  103,  206,  201,  206,  104,  200,  199,

       97,  206,  198,  203,   94,  203,  195,   82,   65,  131,
      131,  131,  131,   65,   78,  194,   79,   79,   79,   79,
      137,  137,  137,  193,  192,   80,   80,   80,   81,   80,
      132,  191,  132,   82,  190,  133,  133,  133,  133,  189,
       79,   80,   83,   80,   81,   80,  188,  206,  134,  206,
      134,   84,   82,  135,  135,  135,  135,  167,   85,   89,
       89,   89,   89,  162,  162,  162,  162,  183,   89,   89,
       89,   89,   89,   90,   90,   90,   91,   90,   90,   90,
      182,  181,  180,   89,   89,   89,   89,   89,   89,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,

       90,   90,   90,   90,   90,   90,  135,  135,  135,  135,
      179,   90,   90,   90,   90,   90,  134,  178,  134,   90,
      177,  139,  139,  139,  139,  176,   90,   90,   90,   90,
       90,   90,  119,  175,  174,  120,  160,  160,  160,  160,
      173,  166,  166,  166,  121,  165,  165,  172,  161,  171,
      163,  163,  163,  163,  170,  164,  164,  164,  164,  167,
      160,  159,   82,  158,  161,  166,  122,   82,  157,  165,
      123,  156,  155,  124,  163,  154,  153,  152,  125,  164,
      126,  151,  127,  150,  128,  169,  169,  169,  169,  160,
      160,  160,  160,  185,  185,  185,  185,  184,  149,  184,

      148,  161,  185,  185,  185,  185,  166,  166,  166,  169,
      147,  146,  145,  160,  144,  143,  142,  161,  186,  186,
      186,  186,  164,  164,  164,  164,  169,  169,  169,  169,
      166,  196,  196,  196,  196,  186,  186,  186,  186,  141,
      140,   82,  186,  129,   66,  117,  164,  115,  114,  112,
      169,  196,  196,  196,  196,  196,  111,  110,  109,  186,
      205,  205,  205,  205,  205,  205,  205,  205,  108,  107,
      106,  105,  101,  100,   99,  196,   98,   95,   92,   88,
       87,   86,   72,   71,  205,   70,   69,   68,  205,   55,
       55,   55,   55,   55,   55,   55,   55,   59,   59,   59,

       59,   59,   59,   59,   59,   62,   62,   62,   62,   62,
       62,   62,   62,  113,   67,  113,  113,  113,  113,  113,
      113,  116,   66,  116,  116,  116,  116,  116,  116,  118,
      206,  206,  118,  118,  118,  118,  118,  130,  206,  130,
      130,  130,  130,  130,  130,   80,   80,   80,  168,  168,
      206,  168,  197,  197,  197,  204,  206,  204,    9,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,

      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206
    } ;

static const flex_int16_t yy_chk[522] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    6,    5,    6,   22,   22,
        3,    4,    7,   24,    7,    3,    4,    8,   24,    8,
       26,   34,   37,   44,  217,   79,   24,  215,  197,   26,
       83,   83,  194,   44,   79,  191,   26,   44,  189,  188,

       37,   79,  187,  198,   34,  198,  183,   83,    7,   78,
       78,   78,   78,    8,   25,  181,   25,   25,   25,   25,
       84,   84,   84,  179,  177,   25,   25,   25,   25,   25,
       81,  175,   81,   25,  173,   81,   81,   81,   81,  172,
       25,   25,   25,   25,   25,   25,  171,  203,   82,  203,
       82,   25,   81,   82,   82,   82,   82,  168,   25,   32,
       32,   32,   32,  132,  132,  132,  132,  158,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
      156,  155,  152,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,

       32,   32,   36,   36,   36,   36,  134,  134,  134,  134,
      150,   36,   36,   36,   36,   36,   91,  149,   91,   36,
      148,   91,   91,   91,   91,  147,   36,   36,   36,   36,
       36,   36,   65,  146,  144,   65,  131,  131,  131,  131,
      143,  137,  137,  137,   65,  136,  136,  142,  131,  141,
      133,  133,  133,  133,  140,  135,  135,  135,  135,  138,
      131,  117,  136,  111,  131,  137,   65,  133,  110,  136,
       65,  109,  108,   65,  133,  107,  106,  104,   65,  135,
       65,  103,   65,  102,   65,  139,  139,  139,  139,  160,
      160,  160,  160,  184,  184,  184,  184,  161,  101,  161,

      100,  160,  161,  161,  161,  161,  166,  166,  166,  139,
       99,   98,   97,  160,   96,   95,   94,  160,  162,  162,
      162,  162,  164,  164,  164,  164,  169,  169,  169,  169,
      166,  185,  185,  185,  185,  186,  186,  186,  186,   93,
       92,   80,  162,   68,   66,   61,  164,   58,   57,   53,
      169,  196,  196,  196,  196,  185,   51,   50,   49,  186,
      204,  204,  204,  204,  205,  205,  205,  205,   48,   47,
       46,   45,   43,   42,   39,  196,   38,   35,   33,   31,
       30,   29,   20,   19,  204,   16,   15,   14,  205,  207,
      207,  207,  207,  207,  207,  207,  207,  208,  208,  208,

      208,  208,  208,  208,  208,  209,  209,  209,  209,  209,
      209,  209,  209,  210,   13,  210,  210,  210,  210,  210,
      210,  211,   11,  211,  211,  211,  211,  211,  211,  212,
        9,    0,  212,  212,  212,  212,  212,  213,    0,  213,
      213,  213,  213,  213,  213,  214,  214,  214,  216,  216,
        0,  216,  218,  218,  218,  219,    0,  219,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,

      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[87] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 
    0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"



#line 20 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
#define YY_NO_UNISTD_H 1
#include "swift.tab.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <string>
using namespace std;


#ifdef _WIN32
    #include "unistd.h"
    #include <io.h>
    #define isatty _isatty
    #define fileno _fileno
    #define read   _read
    #define write  _write
#else
    #include <unistd.h>
#endif


static string stripUnderscores(const char* txt) {
    string clean;
    for (const char* p = txt; *p; ++p) {
        if (*p != '_') clean += *p;
    }
    return clean;
}
#line 694 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\lex.yy.c"
#line 695 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\lex.yy.c"

#define INITIAL 0
#define COMMENT_MULTILINE 1
#define STRING_MULTILINE 2
#define STRING 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 52 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"


#line 55 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
    static int lineNumber = 1;
    static string strBuf;
    static int commentDepth = 0;

#line 923 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 207 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 206 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 59 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ lineNumber++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 61 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"CLASS\" " << yytext << '\n'; return CLASS; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 62 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"FUNC\" " << yytext << '\n'; return FUNC;   }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 63 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"VAR\" "  << yytext << '\n'; return VAR_KW; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 64 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"LET\" "  << yytext << '\n'; return LET_KW; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 65 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"IF\" "   << yytext << '\n'; return IF;     }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 66 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"ELSE\" " << yytext << '\n'; return ELSE;   }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 67 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"FOR\" "  << yytext << '\n'; return FOR;    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 68 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"WHILE\" "<< yytext << '\n'; return WHILE;  }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 69 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"RETURN\" "<< yytext << '\n'; return RETURN;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 70 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"TRUE\" " << yytext << '\n'; yylval.boolVal = true; return TRUE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 71 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"FALSE\" "<< yytext << '\n'; yylval.boolVal = false; return FALSE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 72 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"NIL\" "  << yytext << '\n'; return NIL;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"TYPE_BOOL\" "      << yytext << '\n'; return BOOL_KW; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"TYPE_STRING\" "    << yytext << '\n'; return STRING_KW; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"TYPE_INT\" "       << yytext << '\n'; return INT_KW; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"TYPE_UINT\" "      << yytext << '\n'; return UINT_KW; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"TYPE_FLOAT\" "     << yytext << '\n'; return FLOAT_KW; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"TYPE_DOUBLE\" "    << yytext << '\n'; return DOUBLE_KW; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 83 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{cout << "\"INIT\" "   << yytext << '\n'; yylval.Id = new std::string(yytext); return INIT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 84 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{cout << "\"DEINIT\" " << yytext << '\n'; yylval.Id = new std::string(yytext); return DEINIT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 86 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ 
    yylval.Id = new std::string(yytext);
    cout << "\"IDENTIFIER\" " << yytext << '\n';
    return ID;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 93 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{
    string clean = stripUnderscores(yytext);
    double val = strtod(clean.c_str(), nullptr);
    yylval.Float = val;
    cout << "\"LITERAL_FLOAT_HEX\" " << val << '\n';
    return FLOAT_DEC;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 101 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{
    string clean = stripUnderscores(yytext);
    double val = strtod(clean.c_str(), nullptr);
    yylval.Float = val;
    cout << "\"LITERAL_FLOAT_DEC\" " << val << '\n';
    return FLOAT_DEC;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 109 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{
    string clean = stripUnderscores(yytext + 2); 
    unsigned long long val = strtoull(clean.c_str(), nullptr, 2);
    yylval.Int = val;
    cout << "\"LITERAL_INT_BINARY\" " << val << '\n';
    return INT_DEC;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 117 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{
    string clean = stripUnderscores(yytext + 2);
    unsigned long long val = strtoull(clean.c_str(), nullptr, 8);
    yylval.Int = val;
    cout << "\"LITERAL_INT_OCTAL\" " << val << '\n';
    return INT_DEC;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 125 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{
    string clean = stripUnderscores(yytext);
    unsigned long long val = strtoull(clean.c_str(), nullptr, 16);
    yylval.Int = val;
    cout << "\"LITERAL_INT_HEX\" " << val << '\n';
    return INT_DEC;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 133 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{
    string clean = stripUnderscores(yytext);
    long long val = strtoll(clean.c_str(), nullptr, 10);
    yylval.Int = val;
    cout << "\"LITERAL_INT_DEC\" " << val << '\n';
    return INT_DEC;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 141 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ strBuf = "\""; BEGIN(STRING); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 142 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ 
                     strBuf += yytext;
                     yylval.Id = new std::string(strBuf);
                     return STRING_C;
                   }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 147 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ strBuf += "\\"; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 148 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ strBuf += "\n"; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 149 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ strBuf += "\b"; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 150 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ strBuf += "\0"; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 151 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ strBuf += "\f"; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 152 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ strBuf += "\r"; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 153 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ strBuf += "\t"; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 154 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ strBuf += "\v"; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 155 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ strBuf += "'"; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 156 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ strBuf += "\""; }
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 157 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{
    cout << "ERROR: unterminated string at line " << lineNumber << '\n';
    BEGIN(INITIAL);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 161 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{
    strBuf += "\"";
    cout << "\"LITERAL_STRING\" " << strBuf << '\n';
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 166 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{
    cout << "ERROR: string isn't closed at end of file\n";
    BEGIN(INITIAL);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 171 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"PLUS_ASSIGN\" " << yytext << '\n'; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 172 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"MINUS_ASSIGN\" " << yytext << '\n'; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 173 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"DIV_ASSIGN\" " << yytext << '\n'; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 174 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"MUL_ASSIGN\" " << yytext << '\n'; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 175 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"MOD_ASSIGN\" " << yytext << '\n'; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 177 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"EQ\" " << yytext << '\n';  return EQ;  }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 178 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"NEQ\" " << yytext << '\n'; return NE;  }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 179 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"LTE\" " << yytext << '\n'; return LE;  }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 180 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"GTE\" " << yytext << '\n'; return GE;  }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 181 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"OR\" " << yytext << '\n';  return OR;  }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 182 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"AND\" " << yytext << '\n'; return AND; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 184 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ 
        cout << "\"ASSIGN\" " << yytext << '\n';
        return '='; 
     }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 188 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"LT\" " << yytext << '\n';        return '<';   }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 189 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"GT\" " << yytext << '\n';        return '>';   }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 190 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"DOT\" " << yytext << '\n';       return '.';   }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 191 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"COMMA\" " << yytext << '\n';     return ',';   }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 192 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"SEMICOLON\" " << yytext << '\n'; return ';';   }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 193 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"COLON\" " << yytext << '\n';     return ':';   }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 194 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"ARROW\" " << yytext << '\n';     return ARROW; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 196 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"PLUS\" " << yytext << '\n';  return '+'; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 197 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"MINUS\" " << yytext << '\n'; return '-'; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 198 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"MUL\" " << yytext << '\n';   return '*'; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 199 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"DIV\" " << yytext << '\n';   return '/'; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 200 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"MOD\" " << yytext << '\n';   return '%'; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 201 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"NOT\" " << yytext << '\n';  return NOT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 203 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"LPAREN\" " << yytext << '\n';   return '('; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 204 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"RPAREN\" " << yytext << '\n';   return ')'; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 205 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"LBRACKET\" " << yytext << '\n'; return '['; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 206 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"RBRACKET\" " << yytext << '\n'; return ']'; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 207 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"LBRACE\" " << yytext << '\n';   return '{'; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 208 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"RBRACE\" " << yytext << '\n';   return '}'; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 211 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ strBuf = "\"\"\""; BEGIN(STRING_MULTILINE); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 212 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{
    strBuf += "\"\"\"";
    cout << "\"LITERAL_STRING\" " << strBuf << '\n';
    BEGIN(INITIAL);
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 217 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ strBuf += yytext; }
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 218 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ strBuf += "\n"; lineNumber++; }
	YY_BREAK
case YY_STATE_EOF(STRING_MULTILINE):
#line 219 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{
    cout << "ERROR: unterminated multiline string\n";
    BEGIN(INITIAL);
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 224 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"INLINE_COMMENT\" " << yytext << '\n'; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 226 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ commentDepth = 1; strBuf.clear(); BEGIN(COMMENT_MULTILINE); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 227 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ commentDepth++; strBuf += yytext; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 228 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{
    commentDepth--;
    if (commentDepth == 0) {
        cout << "\"MULTILINE_COMMENT\" " << strBuf << '\n';
        BEGIN(INITIAL);
    } else strBuf += yytext;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 235 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ strBuf += yytext; }
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 236 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ strBuf += "\n"; lineNumber++; }
	YY_BREAK
case YY_STATE_EOF(COMMENT_MULTILINE):
#line 237 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{
    cout << "ERROR: unterminated multiline comment\n";
    BEGIN(INITIAL);
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 242 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ /* skip */ }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 244 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
{ cout << "\"UNKNOWN\" " << yytext << '\n'; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 246 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"
ECHO;
	YY_BREAK
#line 1505 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 207 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 207 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 206);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 246 "F:\\visualStudioProjects\\SwiftLexer\\SwiftLexer\\swift.l"

